name: GitHub Actions Build and Deploy cauu.github.io

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: cauu/github-pages-deploy-action@releases/v3-dev
      with:
        TARGET_REPO: cauu/cauu.github.io,
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: public
        BUILD_SCRIPT: npm install && npm run build
